import {calculateAbility} from "../helpers/ability";
import {calculateFromRolls, type Roll} from "../helpers/rollDice";

/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class huyenvietvttActor extends Actor {
    /** @override */
    prepareData() {
        // Prepare data for the actors. Calling the super version of this executes
        // the following, in order: data reset (to clear active effects),
        // prepareBaseData(), prepareEmbeddedDocuments() (including active effects),
        // prepareDerivedData().
        super.prepareData();

        // console.clear()
        console.log("NEW FROM TS")
        const system = this.system

        // khoi tao thong so
        system.abilities ??= calculateAbility()

        console.log('====')
        console.log(system)
    }

    /** @override */
    prepareBaseData() {
        // Data modifications in this step occur before processing embedded
        // documents or derived data.
    }

    /**
     * @override
     * Augment the actors source data with additional dynamic data that isn't
     * handled by the actors's DataModel. Data calculated in this step should be
     * available both inside and outside of character sheets (such as if an actors
     * is queried and has a roll executed directly from it).
     */
    prepareDerivedData() {
        const actorData = this;
        const flags = actorData.flags.huyenvietvtt || {};
    }

    /**
     *
     * @override
     * Augment the actors's default getRollData() method by appending the data object
     * generated by the its DataModel's getRollData(), or null. This polymorphic
     * approach is useful when you have actors & items that share a parent Document,
     * but have slightly different data preparation needs.
     */
    getRollData() {
        return { ...super.getRollData(), ...(this.system.getRollData?.() ?? null) };
    }

    async rollCheck({} = {}) {
        let diceCount = 2
        const roll = await (new Roll(`${diceCount}d10`)).evaluate();

        const diceResults: number[] = []
        const diceData: Roll[] = roll.dice[0].results.map((r) => {
            diceResults.push(r.result)
            return {
                value: r.result,
                rerollFrom: null
            }
        });

        await ChatMessage.create({
            speaker: ChatMessage.getSpeaker({ actor: this}),
            content: `${diceCount}d10 <==== ${diceResults.join(",")}`,
        })

        console.log(`---You rolled the dice`)
        return calculateFromRolls(diceData)
    }
}
